### PR TITLE
Hi!

### PR DESCRIPTION
**Pull request by iHunter69**
i want just to know if this is an updated and fixed version for the tool because the one im using is from deadbread which he claimed to have been outdated does this one works? i also have token generator which idk how to make it work it shows an error, but is this a fixed version?

### CODE REVIEW

**Comment by Itsmeerez** [comment]
> this is not a fixed version. deadbread's tool still mostly works, although there still might be some things that might not work.

so this dont work?

**Comment by hidden-r4d** [comment]
it works, but some parts of it might not sometimes

**Comment by Itsmeerez** [comment]
> it works, but some parts of it might not sometimes

aight thanks my g

**Comment by Mattlau04** [comment]
closing since not an actual PR

**Pull request closed without merging**
