### PR TITLE
Added option for message spammer at intervals, you can now pick your own endpoint, and fixed checker v1

### PR DESCRIPTION
**Pull request by hidden-r4d**
The message spammer can now spam at intervals of the user's choice.

### CODE REVIEW

**Comment by DavidJosephKhariKonyIIIofUganda** [comment]
i cum

**Comment by DavidJosephKhariKonyIIIofUganda** [comment]
:DDD

**Review by alivx — CHANGES_REQUESTED** [review]
if you replaced 'speed' with more meaningful word that will be better

**Comment by hidden-r4d** [comment]
> if you replaced 'speed' with more meaningful word that will be better

What would you suggest? I'm not really sure of a short word that would convey the idea of what it does easily to the user.

**Comment by alivx** [comment]
> > if you replaced 'speed' with more meaningful word that will be better
> 
> What would you suggest? I'm not really sure of a short word that would convey the idea of what it does easily to the user.

For the more meaningful name you can use (interval) :)

**Review by alivx — APPROVED** [review]

**Comment by DeadBread76** [comment]
any reason why you are making it a float and then an int?

**Comment by hidden-r4d** [comment]
> any reason why you are making it a float and then an int?

To allow people to use things like .7 or 1.8 seconds (maybe this isn't necessary and I'm just dumb)

**Comment by hidden-r4d** [comment]
I am so smart

**Comment by DavidJosephKhariKonyIIIofUganda** [comment]
> any reason why you are making it a float and then an int?

RABE :DDD

**Comment by hidden-r4d** [comment]
git is hard

**Comment by DeadBread76** [comment]
the way i set this repo up kinda sucks and how it does version checking but i will merge it anyway

**Comment by DeadBread76** [comment]
Thanks for doing all this :)

**Comment by hidden-r4d** [comment]
> Thanks for doing all this :)

Just glad to help make a tool that I've gotten a lot out of better.

**Comment by DavidJosephKhariKonyIIIofUganda** [comment]
> Thanks for doing all this :)

I'll get you

**Comment by DavidJosephKhariKonyIIIofUganda** [comment]
> the way i set this repo up kinda sucks and how it does version checking but i will merge it anyway
Its only a six months journey to Australia by sail boat where I am.

**Comment by DavidJosephKhariKonyIIIofUganda** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by DeadBread76** [comment]
> 
> 
> > the way i set this repo up kinda sucks and how it does version checking but i will merge it anyway
> 
> Its only a six months journey to Australia by sail boat where I am.

🤔

**Pull request merged**
