### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Pinguin22**

### CODE REVIEW

**Comment by DeadBread76** [comment]
another nice job idiot

**Comment by Pinguin22** [comment]
Why?

mie., 13 ian. 2021, 16:11 DeadBread76 <notifications@github.com> a scris:

**Comment by Pinguin22** [comment]
Fut pe taktu suck

mie., 13 ian. 2021, 16:11 DeadBread76 <notifications@github.com> a scris:

**Comment by Mattlau04** [comment]
lmfao

**Pull request closed without merging**
